name: 刷步数

on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  schedule:
    - cron: '12 2,4,7,10,12,13 * * *'
  watch:
    types: started
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v4
      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y
          
      - name: 初始化Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: 开始
        run: |
          pip3 install requests
          user='${{ secrets.USER }}'
          passwd='${{ secrets.PWD }}' 
          open_get_weather='${{ secrets.OPEN_GET_WEATHER }}'
          area='${{ secrets.AREA }}'
          sckey='${{ secrets.SCKEY }}'
          python3 main.py ${user} ${passwd} ${open_get_weather} ${area} ${sckey}
          time=$(TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S')
          echo "最后一次运行时间: $time（北京时间）"
